const DEFINE = {};

DEFINE.MONTHES_FOR_YEAR = 12;
DEFINE.DAYS_FOR_WEEK = 7;

DEFINE.DAYS_OF_LEAP_YEAR = 366;
DEFINE.DAYS_OF_NORMAL_YEAR = 365;

DEFINE.SOLAR_TERMS_COUNT = 24;

DEFINE.HEAVENLY_STEMS = 10;
DEFINE.EARTHLY_BRANCHES = 12;
DEFINE.CHINESE_SHENGXIAO = 12;
DEFINE.MAX_GREGORIAN_MONTH_DAYS = 31;

DEFINE.MAX_CHINESE_MONTH_DAYS = 30;
DEFINE.CHINESE_L_MONTH_DAYS = 30;
DEFINE.CHINESE_S_MONTH_DAYS = 29;
DEFINE.MAX_CHINESE_MONTH_FOR_YEAR = 13;

DEFINE.JD2000 = 2451545.0;

// 圆周率
DEFINE.PI = 3.1415926535897932384626433832795;

//每弧度的角秒数
DEFINE.ARC_SEC_PER_RADIAN = (180.0 * 3600.0) / PI;
// 一度代表的弧度
DEFINE.RADIAN_PER_ANGLE = PI / 180.0;

DEFINE.SUN_EL_V = 360.0 / 365.2422;
//DEFINE. MOON_EL_V = 360.0 / 29.53058886;
DEFINE.MOON_EL_V = 360.0 / 27.32;

// typedef  SOLAR_TERMS;

// 节气定义
DEFINE.VERNAL_EQUINOX = 0; // 春分
DEFINE.CLEAR_AND_BRIGHT = 1; // 清明
DEFINE.GRAIN_RAIN = 2; // 谷雨
DEFINE.SUMMER_BEGINS = 3; // 立夏
DEFINE.GRAIN_BUDS = 4; // 小满
DEFINE.GRAIN_IN_EAR = 5; // 芒种
DEFINE.SUMMER_SOLSTICE = 6; // 夏至
DEFINE.SLIGHT_HEAT = 7; // 小暑
DEFINE.GREAT_HEAT = 8; // 大暑
DEFINE.AUTUMN_BEGINS = 9; // 立秋
DEFINE.STOPPING_THE_HEAT = 10; // 处暑
DEFINE.WHITE_DEWS = 11; // 白露
DEFINE.AUTUMN_EQUINOX = 12; // 秋分
DEFINE.COLD_DEWS = 13; // 寒露
DEFINE.HOAR_FROST_FALLS = 14; // 霜降
DEFINE.WER_BEGINS = 15; // 立冬
DEFINE.LIGHT_SNOW = 16; // 小雪
DEFINE.HEAVY_SNOW = 17; // 大雪
DEFINE.WER_SOLSTICE = 18; // 冬至
DEFINE.SLIGHT_COLD = 19; // 小寒
DEFINE.GREAT_COLD = 20; // 大寒
DEFINE.SPRING_BEGINS = 21; // 立春
DEFINE.THE_RAINS = 22; // 雨水
DEFINE.INSECTS_AWAKEN = 23; // 惊蛰

DEFINE.COUNT_ITEM = x => {
  return x.length;
};

module.exports.DEFINE = DEFINE;