name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [master-no-emit]
  push:
    branches: [master-no-emit]

jobs:
  # test-deploy:
  #   if: github.event_name != 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: yarn
  #     - name: Install dependencies
  #       run: yarn install
  #     - name: Test build website
  #       run: yarn build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "jeiizou@qq.com"
          git config --global user.name "jeiizou"
          cd web-sites/wiki-site
          pnpm run deploy
